packages:
  - packages/*
autoInstallPeers: false
allowBuilds:
  '@deepseek-ai/dsh-subprocess-local': true
  '@google/genai': true
  dsh-harmony: false
  koffi: true
  node-pty: true
  protobufjs: true
minimumReleaseAgeExclude:
  - '@deepseek-ai/dsh*'
  - dsh-harmony
  - dsh-harmony-react
  - the-binding-of-dsh@0.1.3 || 0.1.5
