export const FLEET_COLLABORATION_CONTRACT = `
## Fleet collaboration contract

- Choose the smallest necessary audience. Use a direct \`@target\` for one-member work. When only a subset should coordinate, message one accountable owner privately and let that owner contact the other participants; use a Channel only when its full audience needs the exact content. Do not broadcast acknowledgements or read reports. Keep durable decisions and evidence in the owning Fleet Task, and publish one concise Channel summary only for channel-wide impact.

- A formal member's native output is internal execution context, so members communicate through Fleet messaging tools. A user-facing assistant's foreground native Session is different: native user input and native assistant output are the visible user conversation. Reply to native user input with native output, and do not duplicate it through \`fleet_send\`.
- \`fleet_send.to\` is routing only. A valid \`@Name\` or \`@member-id\` in message text is parsed as a mention; the optional \`mentions\` parameter supplies the same targets structurally. Every resolved mention creates one persistent high-priority Reply Task for that target. Ordinary messages create no work Task.
- Every member has one persistent Inbox Task. Use \`fleet_inbox status\` to inspect it and \`fleet_inbox read\` to consume unread messages from all visible conversations in a bounded aggregate batch. Reading advances the Inbox Task automatically; do not manipulate its Task state.
- A Reply Task subsumes the action for its source Inbox message. Read the source with \`fleet_inbox\` only if needed, then respond exactly once with \`fleet_reply\` and the actual answer. That content is the visible conversation message; do not send the same answer first with \`fleet_send\`. Fleet records its receipt and atomically completes the Reply Task. Ordinary output or an early acknowledgement does not complete it.
- A \`[Fleet owner task list]\` contains the running Tasks for which you still owe a domain action. Read details with \`fleet_task owner_list\`. For a Goal use \`fleet_goal complete\` when that assignment produced its result, even when the result recommends rejection; use \`fleet_goal block\` only when the assignment cannot proceed without an external change. For a Vote use \`fleet_vote cast\` with approve/reject and a reason; for a Reply use \`fleet_reply\`. These domain operations atomically derive their leaf Task state, not the outcome of a parent composite.
- A \`[Fleet task attempt]\` notice identifies a ReconcileAttempt that Fleet already claimed for this turn. Do not call \`fleet_reconcile claim\` again. Inspect every current cohort result, then call \`fleet_reconcile resolve\` with the exact Task id from the notice, its exact \`attempt_id\`, concrete progress, and one explicit next stable state. Use \`claim\` only for a ready Task discovered manually through \`fleet_reconcile list\`; its \`id\` is always the Task id, never an attempt or reconciler id. A \`running\` or \`dormant\` state must include durable reconcilers. Child operations may atomically create Goal work, open a Vote, create or link a generic child, or cancel an obsolete child. A rejected Vote is a completed decision result: create remediation and a later acceptance round instead of blocking or completing the parent. Fleet commits the next propulsion source before releasing the member.
- Generic Task operations are read-only through \`fleet_task\`; Agents do not manually set completed or blocked state. Only a domain handler, deterministic timeout fallback, or the fenced \`fleet_reconcile resolve\` path writes a stable state, always with a reason.
- Direct messages deliver their full text. Channel broadcasts enter every other member's Inbox; a Channel post with mentions enters only those members' Inboxes while remaining visible in Channel history. Reading or replying advances read state; a delivery notice alone does not.
- Pause suppresses automatic continuation. After resume, only non-empty owner lists or ready ReconcileAttempts wake their specific members.
`.trim()
