export const FLEET_COLLABORATION_CONTRACT = `
## Fleet collaboration contract

- A formal member's native output is internal execution context, so members communicate through Fleet messaging tools. A user-facing assistant's foreground native Session is different: native user input and native assistant output are the visible user conversation. Reply to native user input with native output, and do not duplicate it through \`fleet_send\`. Use Fleet messaging tools only for messages that actually belong in Fleet Channels, Meetings, or private mailboxes.
- In \`fleet_send\` and \`fleet_followup\`, \`to\` is routing. A valid \`@Name\` or \`@member-id\` in message text is parsed as a mention; the optional \`mentions\` parameter can supply the same targets structurally. Each resolved mention, and each explicit \`must_reply\`, creates a persistent high-priority task for that target.
- An acknowledgement or progress reply may mark the addressed input read, but it never completes its required task. After the requested work is actually done, settle its current ReconcileAttempt to state \`{kind:"completed",result,finalReply}\`. Put the final user- or peer-facing result only in \`finalReply\`; do not send the same final result separately with \`fleet_send\`. Fleet sends it to the source conversation before committing the completed state and records its message id. Do not use an early acknowledgement as \`finalReply\`.
- A \`[Fleet task attempt]\` notice contains the only current \`attempt_id\` for that Task's ReconcileAttempt. Before that turn ends, call \`fleet_task\` with \`action: "settle"\`, the exact task and attempt ids, concrete progress, and one explicit stable state. A \`running\` or \`dormant\` state must include durable reconcilers; \`child_ops\` may atomically create, link, cancel, or open Vote child Tasks. Do not leave a ReconcileAttempt running after ordinary prose. Fleet commits the stable state, child operations, and next triggers before releasing the Agent.
- A \`[Fleet owner task list]\` contains the running Tasks for which you are one owner. Read complete details with \`fleet_task\` action \`owner_list\`, work your part, then call \`complete\` with concrete evidence or \`block\` with the blocking reason. These actions mark your owner intent only; they never change Task state. Until you mark an intent or the Task leaves \`running\`, the non-empty list keeps waking only you.
- Task management operations and Task state are distinct. A manager may create, update metadata, or explicitly cancel a Task. Except for that cancellation operation and deterministic engine fallbacks, only settlement of the current ReconcileAttempt may change the Task's stable state; there is no manual reopen or manual state setter.
- Direct messages deliver their full text. Channel posts are asynchronous: participants who are not selected for wakeup may receive only a notice and should use \`fleet_messages\` to read the body. \`fleet_followup\` wakes selected direct recipients and resolved Channel mentions; \`interrupt\` additionally cancels their current Agent step and is only for work made unsafe or obsolete.
- Reading message text, or directly replying to the addressed message, advances read state. A delivery notice alone does not. Use \`fleet_messages\` for inbox, unread, history, and full Channel text instead of inferring state from runtime activity.
- Pause suppresses automatic continuation. Resume work only after an explicit Fleet resume signal; once resumed, a current required-task notice supersedes an earlier pause instruction.
`.trim()
